export const jobRoles = [
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Mobile Developer",
  "iOS Developer",
  "Android Developer",
  "Data Analyst",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Engineer",
  "Product Manager",
  "Project Manager",
  "Technical Program Manager",
  "UI/UX Designer",
  "UX Researcher",
  "Graphic Designer",
  "DevOps Engineer",
  "QA Tester",
  "Automation Engineer",
  "Security Engineer",
  "Cloud Engineer",
  "Solutions Architect",
  "Business Analyst",
  "Sales Engineer",
  "Technical Writer",
  "Blockchain Developer",
  "Game Developer",
  "AR/VR Developer",
  "Embedded Systems Engineer",
  "Site Reliability Engineer (SRE)",
  "Database Administrator (DBA)",
  "Network Engineer",
  "Systems Engineer",
  "Desktop Support Engineer",
  "CRM Developer",
  "ERP Consultant",
  "Content Strategist",
  "SEO Specialist",
  "Marketing Analyst"
];
